{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <script.test01.Test object at 0x000002F0771FF358>\n\n    def test_3(self):\n>       assert 0\nE       assert 0\n\nscript\\test01.py:11: AssertionError"}, "start": 1609758687567, "stop": 1609758687567, "uuid": "66037730-fa69-4f94-a12a-6e1bb930ff79", "historyId": "1e82aad3aa600717dfda98e01841b586", "testCaseId": "aab81d327047f3a126dd9c6cd90aaea5", "fullName": "script.test01.Test#test_3", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test01"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "PC-20191214RDZJ"}, {"name": "thread", "value": "12032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test01"}]}